version: '3.7'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    hostname: DATABASE-SQL
    volumes:
      - ./sql-data/db:/var/lib/mysql
      - ./init-sql:/docker-entrypoint-initdb.d
      #- ./init-sql:/docker-entrypoint-initdb.d
